name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- matplotlib-base
- numpy
- scipy
- sympy<=1.7.1 # the is required, with the new version sympy 1.8, the load-deflection curve is wrong (TODO, investigate)
- ipywidgets
- ipympl
- pip
- pip:
  - anastruct
  - bmcs-utils
  - bmcs-cross-section
  - bmcs-beam
  - -e .
