name: bmcs_env
channels:
- conda-forge
dependencies:
- traits
- matplotlib
- numpy
- sympy
- scipy
- k3d
- ipywidgets==7.7.0
- ipympl
- ipytree
- shapely
- pandas
- jupyterlab
- importlib_resources
- pip
- pip:
  - anastruct
  - openpyxl
  - bmcs-utils==0.0.32a0
  - bmcs-ibvpy==0.0.25a0
  - bmcs-cross-section==0.0.55a0
