name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- matplotlib-base
- numpy
- scipy
- sympy
- ipywidgets
- ipympl
- pip
- pip:
  - bmcs-utils
  - bmcs-cross-section
  - bmcs-beam
  - -e .
